#!/bin/bash

cmake .. -DCMAKE_BUILD_TYPE=Release -DSC_WII=OFF -DSC_QT=OFF -DSCLANG_SERVER=OFF -DCMAKE_INSTALL_PREFIX=~/software/supercollider/3.5.7

cmake .. -DCMAKE_BUILD_TYPE=Release -DSC_WII=OFF -DSC_QT=OFF -DSCLANG_SERVER=OFF -DCMAKE_INSTALL_PREFIX=~/software/supercollider/3.5.7 -DSYSTEM_BOOST=ON

cmake .. -DCMAKE_BUILD_TYPE=Release -DSC_WII=OFF -DSC_QT=OFF -DSCLANG_SERVER=ON -DCMAKE_INSTALL_PREFIX=~/software/supercollider/3.5.7 -DSYSTEM_BOOST=ON
